// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 28. 01. 2025. 12:25:14
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/Radovi/rijeka-newshop/nk-rijeka-shop/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Radovi/rijeka-newshop/nk-rijeka-shop/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Radovi/rijeka-newshop/nk-rijeka-shop/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Radovi/rijeka-newshop/nk-rijeka-shop/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Radovi/rijeka-newshop/nk-rijeka-shop/plugins/**/*.{js,ts,mjs}","D:/Radovi/rijeka-newshop/nk-rijeka-shop/composables/**/*.{js,ts,mjs}","D:/Radovi/rijeka-newshop/nk-rijeka-shop/utils/**/*.{js,ts,mjs}","D:/Radovi/rijeka-newshop/nk-rijeka-shop/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Radovi/rijeka-newshop/nk-rijeka-shop/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Radovi/rijeka-newshop/nk-rijeka-shop/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;