// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 30. 01. 2025. 15:45:46
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Ivana Cetina/nk-rijeka/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ivana Cetina/nk-rijeka/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ivana Cetina/nk-rijeka/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ivana Cetina/nk-rijeka/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ivana Cetina/nk-rijeka/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ivana Cetina/nk-rijeka/plugins/**/*.{js,ts,mjs}","C:/Users/Ivana Cetina/nk-rijeka/composables/**/*.{js,ts,mjs}","C:/Users/Ivana Cetina/nk-rijeka/utils/**/*.{js,ts,mjs}","C:/Users/Ivana Cetina/nk-rijeka/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ivana Cetina/nk-rijeka/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ivana Cetina/nk-rijeka/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;